### ISSUE TITLE
Missing a file

### ISSUE THREAD

**Issue by Rafcin** [csvance/roboclaw#2]
You seem to be missing RoboclawEncoderSteps.h

**Comment by csvance** [comment]
Did you source your ros workspace setup file before running catkin_make?

ie, `source ~/catkin_ws/devel/setup.bash`

**Comment by Rafcin** [comment]
I can't build the project becuase the file is missing when trying to compile it. You are missing the file I referenced above.

**Comment by csvance** [comment]
RoboclawEncoderSteps.h is a message header file which gets automatically generated by ROS when you run catkin_make.

**Comment by Rafcin** [comment]
That's odd, I can't build it because the files missing. I run it as Catkin
build so it's the same as Catkin make. I'm not quite sure why it doesn't
generate.

**Comment by Rafcin** [comment]
*edit* Huh my bad the file generated. It seems what happened was the catkin build didn't complete the job correctly and never actually made it, running catkin build roboclaw worked just fine!

Sorry for the inconvenience!

**Comment by Achllle** [comment]
I ran into the same issue. Fresh workspace, ROS Melodic. master branch. Sourcing didn't (and shouldn't) make a difference.

```
In file included from /home/test_ws/src/roboclaw/src/diffdrive_roscore.cpp:28:0:
/home/achille/test_ws/src/roboclaw/include/diffdrive_roscore.h:30:10: fatal error: roboclaw/RoboclawEncoderSteps.h: No such file or directory
 #include "roboclaw/RoboclawEncoderSteps.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
roboclaw/CMakeFiles/diffdrive_roscore.dir/build.make:62: recipe for target 'roboclaw/CMakeFiles/diffdrive_roscore.dir/src/diffdrive_roscore.cpp.o' failed
make[2]: *** [roboclaw/CMakeFiles/diffdrive_roscore.dir/src/diffdrive_roscore.cpp.o] Error 1
CMakeFiles/Makefile2:3147: recipe for target 'roboclaw/CMakeFiles/diffdrive_roscore.dir/all' failed
make[1]: *** [roboclaw/CMakeFiles/diffdrive_roscore.dir/all] Error 2
```

Running catkin_make a second time does succeed. This looks like the following ROS answers question: [compile twice to see custom message](https://answers.ros.org/question/173342/compile-twice-to-see-custom-message/)

The reason is suddenly started working for @Rafcin is that he just ran it a second time. @csvance you might want to reopen this issue, happy to create a PR to fix
